name: CD
on:
  push:
    branches:
      - main
      - beta
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: guardian/actions-setup-node@v2.4.1
        with:
          cache: npm
      - name: CD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./script/cd
