name: CD
on:
  push:
    branches:
      - main
jobs:
  CD:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.1]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.4
      with:
        node-version: ${{ matrix.node-version }}
    - name: CD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: ./script/cd
    - name: post-release
      uses: guardian/post-release-action@main
      with:
        # This action will raise a PR to edit package.json.
        # PRs raised by the default `secrets.GIT_TOKEN` will not trigger CI,
        # so we need to provide a different token.
        # This is a PAT for the guardian-ci user.
        # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
        github-token: ${{ secrets.POST_RELEASE_TOKEN }}
