name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  # see https://github.com/marketplace/actions/semantic-pull-request
  lint-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.15.1 ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
      - run: ./script/ci
